# Generated by Django 5.0 on 2024-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(default='10', max_length=200)),
                ('clients', models.CharField(default='10', max_length=200)),
                ('experience', models.CharField(default='1', max_length=200)),
                ('field', models.CharField(default='Web Developer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechStacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechDescription', models.CharField(max_length=200)),
                ('TechsClass', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAndTime', models.DateTimeField(auto_now_add=True)),
                ('contentStart', models.CharField(max_length=200)),
                ('contentMid', models.CharField(max_length=200)),
                ('contentEnd', models.CharField(max_length=200)),
                ('readContentURL', models.CharField(max_length=200)),
            ],
        ),
    ]
