# Generated by Django 5.0 on 2024-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_techlang_techstack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_href', models.CharField(max_length=100)),
                ('contactIcon_class', models.CharField(max_length=100)),
            ],
        ),
    ]
