# Generated by Django 5.0 on 2024-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='target',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
