# Generated by Django 5.0 on 2024-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_contact_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genereOnclick', models.CharField(max_length=100)),
                ('genereId', models.CharField(max_length=100)),
                ('genereName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webLink', models.CharField(max_length=100)),
                ('projectImage', models.ImageField(blank=True, default='projects/default_project.jpg', null=True, upload_to='Projects/')),
                ('projectLogo', models.ImageField(blank=True, default='projectsLogo/default_project_Logo.jpg', null=True, upload_to='ProjectsLogo/')),
                ('projectName', models.CharField(max_length=100)),
                ('projectGit', models.CharField(max_length=100)),
                ('projectAbout', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='projectLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('projectTech', models.ManyToManyField(related_name='projectlang', to='project.projectsmod')),
            ],
        ),
    ]
