# Generated by Django 5.0 on 2024-03-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectsgenere_projectsmod_projectlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsgenere',
            name='prjGen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prjGen', to='project.projectsmod'),
            preserve_default=False,
        ),
    ]
