# Generated by Django 5.0 on 2024-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectsgenere_prjgen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsgenere',
            name='prjGen',
        ),
        migrations.AddField(
            model_name='projectsgenere',
            name='prjGen',
            field=models.ManyToManyField(related_name='prjGen', to='project.projectsmod'),
        ),
    ]
