# Generated by Django 5.0 on 2024-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_projectsgenere_prjgen_projectsgenere_prjgen'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmod',
            name='orderId',
            field=models.IntegerField(default='0'),
        ),
    ]
