# Generated by Django 5.0 on 2024-03-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectsgenere_prjgen'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmod',
            name='webblogLink',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
