# Generated by Django 4.2.9 on 2024-10-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_projectsmod_webbloglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmod',
            name='projectImage',
        ),
        migrations.AlterField(
            model_name='projectsmod',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='projects/default_project.jpg', null=True, upload_to='Projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.projectsmod')),
            ],
        ),
    ]
